# https://blog.travis-ci.com/2015-10-14-opening-up-ubuntu-trusty-beta/
sudo: required
dist: trusty

language: python
python:
  - "3.5"
cache:
  - pip
# if specific versions of docker or docker-compose are needed, see travis-CI docs
services:
  - docker # default is docker 1.8.2 and docker-compose 1.4.2 (as of Oct. 2016)


before_script:
  - mkdir ~/cs4501/
  - mkdir ~/cs4501/db/
  - mkdir ~/cs4501/app/
  - mv -v ./{.[!.],}* ~/cs4501/app/  # moves everything in current root directory to cs4501/app for travis CI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" # X Virtual Framebuffer to imitate a display
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - # install chrome for selenium
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sleep 10
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
  - sleep 60 # need to give time for containers and xvfb to start

script:
  - cd ~/cs4501/app/
  - docker-compose up -d # daemon process -d goes in background
  - cd ~/cs4501/app/web/client/
  - python tests.py
  - sleep 120
  - docker-compose down
#  - >
#    docker exec -it model bash -c
#    "pip install -r requirement.txt && python manage.py test"
#    # run Django unit tests on models
#  - >
#    docker exec -it exp bash -c
#    "pip install -r requirement.txt && python manage.py test"
#    # run Django unit tests on exp
#  - >
#    pip3 install -r requirement.txt && python3 ./misc/selenium/test_front_end_travis.py
#    # run selenium front end tests with xvfb
#after_success:

after_script:
  - docker rm `docker ps -a -q`
  - docker rmi `docker images -q`
  - rm -rf db
