model:
    # build: .
    image: tp33/django 
    container_name: model
    external_links:
      -  mysql:db
    volumes:
      - ./model:/app
    ports:
      - "8001:8000"
    command: bash -c "pip install \"djangorestframework==3.5.3\" && python manage.py makemigrations && python manage.py migrate && python manage.py loaddata fixtures/db.json && mod_wsgi-express start-server --working-directory ./ --reload-on-changes ./model/wsgi.py --log-to-terminal"

exp:
    # build: .
    image: tp33/django 
    container_name: exp
    links:
      - model:model-api
    volumes:
      - ./exp:/app
    ports:
      - "8002:8000"
    command: bash -c "pip install \"requests==2.13.0\" && pip install \"djangorestframework==3.5.3\" && mod_wsgi-express start-server --reload-on-changes ./exp/wsgi.py --log-to-terminal"

web:
    # build: .
    image: tp33/django 
    container_name: web
    links:
      - exp:exp-api
    ports:
      - "8080:8000"
    volumes:
      - ./web:/app
    command: bash -c "pip install \"requests==2.13.0\" && pip install \"djangorestframework==3.5.3\" && mod_wsgi-express start-server --reload-on-changes ./web/wsgi.py --log-to-terminal"
