model:
    image: tp33/django
    external_links:
      -  mysql:db
    volumes:
      - ./:/app
    ports:
      - "8001:8000"
    command: bash -c "python manage.py migrate && python manage.py makemigrations && mod_wsgi-express start-server --working-directory ./ --reload-on-changes ./model/wsgi.py"