# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-09 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carpool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carpool_id', models.TextField()),
                ('driver', models.TextField()),
                ('passengers', models.TextField()),
                ('cost', models.TextField()),
                ('location_start', models.TextField()),
                ('location_end', models.TextField()),
                ('time_leaving', models.TextField()),
                ('time_arrival', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('user_id', models.TextField()),
                ('balance', models.TextField()),
            ],
        ),
    ]
